# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_trace_dat')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_trace_dat')
    _trace_dat = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_trace_dat', [dirname(__file__)])
        except ImportError:
            import _trace_dat
            return _trace_dat
        try:
            _mod = imp.load_module('_trace_dat', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _trace_dat = swig_import_helper()
    del swig_import_helper
else:
    import _trace_dat
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class trace_dat(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, trace_dat, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, trace_dat, name)
    __repr__ = _swig_repr

    def __init__(self, filename: 'std::string'):
        this = _trace_dat.new_trace_dat(filename)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _trace_dat.delete_trace_dat
    __del__ = lambda self: None

    def test(self) -> "std::string":
        return _trace_dat.trace_dat_test(self)

    def events(self) -> "std::vector< std::string >":
        return _trace_dat.trace_dat_events(self)
trace_dat_swigregister = _trace_dat.trace_dat_swigregister
trace_dat_swigregister(trace_dat)

class dat_header_page(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, dat_header_page, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, dat_header_page, name)
    __repr__ = _swig_repr
    __swig_setmethods__["header_page"] = _trace_dat.dat_header_page_header_page_set
    __swig_getmethods__["header_page"] = _trace_dat.dat_header_page_header_page_get
    if _newclass:
        header_page = _swig_property(_trace_dat.dat_header_page_header_page_get, _trace_dat.dat_header_page_header_page_set)
    __swig_setmethods__["header_page_size"] = _trace_dat.dat_header_page_header_page_size_set
    __swig_getmethods__["header_page_size"] = _trace_dat.dat_header_page_header_page_size_get
    if _newclass:
        header_page_size = _swig_property(_trace_dat.dat_header_page_header_page_size_get, _trace_dat.dat_header_page_header_page_size_set)
    __swig_setmethods__["null"] = _trace_dat.dat_header_page_null_set
    __swig_getmethods__["null"] = _trace_dat.dat_header_page_null_get
    if _newclass:
        null = _swig_property(_trace_dat.dat_header_page_null_get, _trace_dat.dat_header_page_null_set)
    __swig_setmethods__["data"] = _trace_dat.dat_header_page_data_set
    __swig_getmethods__["data"] = _trace_dat.dat_header_page_data_get
    if _newclass:
        data = _swig_property(_trace_dat.dat_header_page_data_get, _trace_dat.dat_header_page_data_set)

    def __init__(self):
        this = _trace_dat.new_dat_header_page()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _trace_dat.delete_dat_header_page
    __del__ = lambda self: None
dat_header_page_swigregister = _trace_dat.dat_header_page_swigregister
dat_header_page_swigregister(dat_header_page)

class dat_struct(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, dat_struct, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, dat_struct, name)
    __repr__ = _swig_repr
    __swig_setmethods__["magic_number"] = _trace_dat.dat_struct_magic_number_set
    __swig_getmethods__["magic_number"] = _trace_dat.dat_struct_magic_number_get
    if _newclass:
        magic_number = _swig_property(_trace_dat.dat_struct_magic_number_get, _trace_dat.dat_struct_magic_number_set)
    __swig_setmethods__["Dtracing"] = _trace_dat.dat_struct_Dtracing_set
    __swig_getmethods__["Dtracing"] = _trace_dat.dat_struct_Dtracing_get
    if _newclass:
        Dtracing = _swig_property(_trace_dat.dat_struct_Dtracing_get, _trace_dat.dat_struct_Dtracing_set)
    __swig_setmethods__["null1"] = _trace_dat.dat_struct_null1_set
    __swig_getmethods__["null1"] = _trace_dat.dat_struct_null1_get
    if _newclass:
        null1 = _swig_property(_trace_dat.dat_struct_null1_get, _trace_dat.dat_struct_null1_set)
    __swig_setmethods__["header_page"] = _trace_dat.dat_struct_header_page_set
    __swig_getmethods__["header_page"] = _trace_dat.dat_struct_header_page_get
    if _newclass:
        header_page = _swig_property(_trace_dat.dat_struct_header_page_get, _trace_dat.dat_struct_header_page_set)

    def __init__(self):
        this = _trace_dat.new_dat_struct()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _trace_dat.delete_dat_struct
    __del__ = lambda self: None
dat_struct_swigregister = _trace_dat.dat_struct_swigregister
dat_struct_swigregister(dat_struct)

# This file is compatible with both classic and new-style classes.


